### ISSUE TITLE
lauffähige Version als GitHub page

### ISSUE THREAD

**Issue by jvoigtlaender** [vnoe/nonogram#2]
Wenn eine erste Version lauffähig ist, stellen Sie das Kompilat bitte online zur Verfügung. Dazu einfach die erzeugte `.html` Datei in einen (ansonst leeren) Branch `gh-pages` legen, und in der `README.md` des `master` Branches den entsprechenden Link `https://username.github.io/projectname/filename.html` angeben.

**Comment by vnoe** [comment]
Done
